### ISSUE TITLE
An error was encountered while running the VAE model based on the flows.

### ISSUE THREAD

**Issue by 5466a** [acids-ircam/pytorch_flows#7]
- AttributeError                            Traceback (most recent call last)
- <ipython-input-37-081c502b6f38> in <module>
-       7 block_planar = [PlanarFlow]
-       8 # Create normalizing flow
- ----> 9 flow = NormalizingFlow(dim=n_latent, blocks=block_planar, flow_length=16, density=distrib.MultivariateNormal(torch.zeros(n_latent), torch.eye(n_latent)))
-      10 # Construct encoder and decoder
-      11 encoder, decoder = construct_encoder_decoder(nin, n_hidden = n_hidden, n_latent = n_latent, n_classes = num_classes)
- 
- <ipython-input-26-515ef23fac73> in __init__(self, dim, blocks, flow_length, density)
-      11         self.bijectors = nn.ModuleList(biject)
-      12         self.base_density = density
- ---> 13         self.final_density = distrib.TransformedDistribution(density, self.transforms)
-      14         self.log_det = []
-      15 
- 
- D:\LenovoSoftstore\AI_software\Anaconda3\envs\mainpy\lib\site-packages\torch\distributions\transformed_distribution.py in __init__(self, base_distribution, transforms, validate_args)
-      57         base_event_dim = len(base_distribution.event_shape)
-      58         transform = ComposeTransform(self.transforms)
- ---> 59         domain_event_dim = transform.domain.event_dim
-      60         if len(base_shape) < domain_event_dim:
-      61             raise ValueError("base_distribution needs to have shape with size at least {}, but got {}."
- 
- D:\LenovoSoftstore\AI_software\Anaconda3\envs\mainpy\lib\site-packages\torch\distributions\transforms.py in domain(self)
-     285         if not self.parts:
-     286             return constraints.real
- --> 287         domain = self.parts[0].domain
-     288         # Adjust event_dim to be maximum among all parts.
-     289         event_dim = self.parts[-1].codomain.event_dim
- 
- D:\LenovoSoftstore\AI_software\Anaconda3\envs\mainpy\lib\site-packages\torch\distributions\transforms.py in domain(self)
-     285         if not self.parts:
-     286             return constraints.real
- --> 287         domain = self.parts[0].domain
-     288         # Adjust event_dim to be maximum among all parts.
-     289         event_dim = self.parts[-1].codomain.event_dim
- 
- D:\LenovoSoftstore\AI_software\Anaconda3\envs\mainpy\lib\site-packages\torch\nn\modules\module.py in __getattr__(self, name)
-    1128             if name in modules:
-    1129                 return modules[name]
- -> 1130         raise AttributeError("'{}' object has no attribute '{}'".format(
-    1131             type(self).__name__, name))
-    1132 
- 
- AttributeError: 'PlanarFlow' object has no attribute 'domain'

**Comment by ymashell** [comment]
Could you please share how you solve this "AttributeError: 'PlanarFlow' object has no attribute 'domain'" issue?
Thanks!
